# Generated by Django 5.2.7 on 2025-10-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(help_text='The sequence of the approval, e.g., 1, 2, 3.')),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_manager_default_approver', models.BooleanField(default=True, help_text="If true, the user's manager is automatically the first approver.")),
                ('min_approval_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='e.g., 60.00. Percentage of approvers required to approve.', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
