# Generated by Django 5.2.7 on 2025-10-04 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflowstep',
            name='approver_user',
            field=models.ForeignKey(help_text='The user designated as an approver in this step.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='approvalflowstep',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='admin_dashboard.approvalrule'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalflowstep',
            unique_together={('rule', 'step_order')},
        ),
    ]
